name: Github with JIRA
description: 'ONLY4 Github & Jira 이슈 템플릿입니다.'
title: "[]: "
labels: []
body:
  - type: dropdown
    id: issueType
    attributes:
      label: 📥 Issue Type
      description: 'Jira 이슈 타입을 선택해주세요.'
      options:
        - Task
        - Story
        - 버그
      default: 0
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '📮 상세 내용 Description'
      description: '이슈에 대해서 자세히 설명해주세요'
      value: |
        ### 어떤 작업인가요?
        > 진행할 작업에 대해 간단하게 설명해주세요.

        ## 🔨 상세 작업 내용
        
        - [ ] 
        - [ ]
        
        ## 📄 참고 사항
        
        ## ⏰ 예상 소요 기간

    validations:
      required: true
